version: '3'

services:
  pfred-service:
    image: pfredimg:latest
    ports:
      - "8000:8000"
    container_name:
      pfredservice
    volumes:
      - pfred-vol:/home/pfred

volumes:
  pfred-vol:
