version: '3'

services:
  pfred-service:
    image: pfredimg:latest
    ports:
      - "80:8000"
    container_name:
      "pfred"
    volumes:
      - pfred-volume:/home/pfred

volumes:
  pfred-volume:
